aws:
  dynamodb:
    endpoint: "${AWS_DYNAMO_ENDPOINT:http://localhost:8000}"
entrypoint:
  sqs:
    endpoint: "http://localhost:4566"
    queueUrl: "http://localhost:4566/000000000000/solicitude-report-queue"