aws:
  dynamodb:
    endpoint: "${AWS_DYNAMO_ENDPOINT:http://localhost:8000}"
entrypoint:
  sqs:
    endpoint: "${AWS_SQS_REPORT_ENDPOINT:http://localhost:4566}"
    queueUrl: "${AWS_SQS_REPORT_URL:http://localhost:4566/000000000000/solicitude-report-queue}"
security:
  jwt:
    secret: ${JWT_SECRET:iBdGbA8Dxowf12Zs7IYH91+KwKOg5yb39RGQv6pOWes=}
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8083}"

logging:
  level:
    root: INFO
    co.com.pragma: DEBUG