aws:
  dynamodb:
    endpoint: "${AWS_DYNAMO_ENDPOINT}"
entrypoint:
  sqs:
    endpoint: "${AWS_SQS_REPORT_ENDPOINT}"
    queueUrl: "${AWS_SQS_REPORT_URL}"
security:
  jwt:
    secret: ${JWT_SECRET}

cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"