aws:
  dynamodb:
    endpoint: "${AWS_DYNAMO_ENDPOINT:https://dynamodb.us-east-1.amazonaws.com}"
entrypoint:
  sqs:
    endpoint: "${AWS_SQS_REPORT_ENDPOINT:https://sqs.us-east-1.amazonaws.com}"
    queueUrl: "${AWS_SQS_REPORT_URL:https://sqs.us-east-1.amazonaws.com/096187159240/solicitude-report-queue}"